export const HindiHits = [
	{
		album: { browseId: 'UCSYa5_xCD-0iSwqeHjwx5Sw', name: 'Akhil' },
		artist: 'Akhil, Dhvani Bhanushali, ',
		duration: 222000,
		formatedDuration: '03:42',
		name: 'Duniyaa (From "Luka Chuppi")',
		params: 'wAEB',
		playlistId: 'RDAMVMh3EuilWNquo',
		thumbnails:
			'https://lh3.googleusercontent.com/kpmaPayRqAm6Ol1j_uYIQvxvDHVBEdW7RM5YSGNud0n36onW-W0lITnTv9YE9tN6Jx3s8JvcvfrA7Pax_w=w400-h400-l90-rj',
		type: 'song',
		videoId: 'h3EuilWNquo',
	},
	{
		album: { browseId: 'UCXgL1dALW24g-ND8ofzSLKg', name: 'Diler Kharkiya' },
		artist: 'Diler Kharkiya',
		duration: 210000,
		formatedDuration: '03:30',
		name: 'Wish',
		params: 'wAEB',
		playlistId: 'RDAMVMy-nRD-9QyOA',
		thumbnails:
			'https://lh3.googleusercontent.com/Ed2lVbGhTHn4FoXP9vyjfqyrIC50FOqXskbSQIqrrL_akuz8wSds8XXO0McWd_GAqezUb_KozOiD1N0=w400-h400-l90-rj',
		type: 'song',
		videoId: 'y-nRD-9QyOA',
	},
	{
		album: { browseId: 'UCDxKh1gFWeYsqePvgVzmPoQ', name: 'Arijit Singh' },
		artist: 'Arijit Singh, Alka Yagnik, ',
		duration: 341000,
		formatedDuration: '05:41',
		name: 'Agar Tum Saath Ho',
		params: 'wAEB',
		playlistId: 'RDAMVMFOA9iyxsW_A',
		thumbnails:
			'https://lh3.googleusercontent.com/AT2wfk1PvKjnHO7BzH2i2NkAvqRy_oZNEq48QGBlLJb51AuguCiR3mzp99X1uFdZezAkoSJ2WGjUU-HXZg=w400-h400-l90-rj',
		type: 'song',
		videoId: 'FOA9iyxsW_A',
	},
	{
		album: { browseId: 'UCmIJDVHH-W5eILcGPos_rKA', name: 'Mika Singh' },
		artist: 'Mika Singh, Payal Dev, ',
		duration: 227000,
		formatedDuration: '03:47',
		name: 'Sawan Mein Lag Gayi Aag',
		params: 'wAEB',
		playlistId: 'RDAMVMT0k40HGNoEw',
		thumbnails:
			'https://lh3.googleusercontent.com/JKs2kRuh_-xYxGJFQSDKSAuUdfUFOWgmtbvWlIrVQ5xIcQPXzWVIzkd_X52uVyIojDbP6gpg3URTp9s=w400-h400-l90-rj',
		type: 'song',
		videoId: 'T0k40HGNoEw',
	},
	{
		album: { browseId: 'UCsmm-jjSLILh12mZ2aR6Qrg', name: 'Neha Kakkar' },
		artist: 'Neha Kakkar, Jubin Nautiyal, ',
		duration: 231000,
		formatedDuration: '03:51',
		name: 'Taaron Ke Shehar',
		params: 'wAEB',
		playlistId: 'RDAMVMUO8D53fjxqk',
		thumbnails:
			'https://lh3.googleusercontent.com/ySQJVZ06j7RWqt3jbjLyUYtVzvP4-mDKFj2s_RsjzSF5gLStMRzr-pOXwT9NssZvDo1G6mMpkVw0PA4P=w400-h400-l90-rj',
		type: 'song',
		videoId: 'UO8D53fjxqk',
	},
	{
		album: { browseId: 'UC8NZlgLbWrCsHL_4WPtuSWQ', name: 'Shashi' },
		artist: 'Shashi, DJ Khushi, Nikhita Gandhi, Madhubanti Bagchi, ',
		duration: 188000,
		formatedDuration: '03:08',
		name: 'BurjKhalifa (From "Laxmii")',
		params: 'wAEB',
		playlistId: 'RDAMVMmYfWMwjFRcQ',
		thumbnails:
			'https://lh3.googleusercontent.com/yFfWquLr9iUUtn3ILumWfBPvTmWsjgDzO-FMxOynzxZCS2k_YKnOZBRfsvUn_pipH_21o7-Gsn53PeeC=w400-h400-l90-rj',
		type: 'song',
		videoId: 'mYfWMwjFRcQ',
	},
	{
		album: { browseId: 'UCuqZRvxO_-lqdHQRH8jVt1w', name: 'Afsana Khan' },
		artist: 'Afsana Khan',
		duration: 196000,
		formatedDuration: '03:16',
		name: 'Titliaan (feat. Harrdy Sandhu & Sargun Mehta)',
		params: 'wAEB',
		playlistId: 'RDAMVMvoFhlwj8ITs',
		thumbnails:
			'https://lh3.googleusercontent.com/uXJcQrhwlSTwi0Ftzs-8GQlWC04xQe4fVMkP-sW0YXsEG62vq1iU6BCVITWbE8H-3SsU5w21Lqf-p4ud=w400-h400-l90-rj',
		type: 'song',
		videoId: 'voFhlwj8ITs',
	},
	{
		album: { browseId: 'UCdWuR07og626xwU93eSCh9A', name: 'Jubin Nautiyal' },
		artist: 'Jubin Nautiyal, Rochak Kohli, ',
		duration: 243000,
		formatedDuration: '04:03',
		name: 'Bewafa Tera Masoom Chehra',
		params: 'wAEB',
		playlistId: 'RDAMVMESiY1AXXWrI',
		thumbnails:
			'https://lh3.googleusercontent.com/dwrc2E2b4h1o2W0rxnzl0iKMLlAiyFwuHT99dqmgx2OTheiOCo9QzuyVxAVknljkCWnY-czpRxhs9zIz=w400-h400-l90-rj',
		type: 'song',
		videoId: 'ESiY1AXXWrI',
	},
	{
		album: { browseId: 'UCaXkLshDZPsz-UBudwEBOLw', name: 'Pawni Pandey' },
		artist: 'Pawni Pandey',
		duration: 306000,
		formatedDuration: '05:06',
		name: 'Laila Main Laila',
		params: 'wAEB',
		playlistId: 'RDAMVM-0YEJbeTXEk',
		thumbnails:
			'https://lh3.googleusercontent.com/4JskAQe7v1sy1L9lm8MLtKgQanhm4Y87hPhl32Ayxr0by8L2uYf6mc5XIQ2wgGpTSCBrYJrOXX19I21p=w400-h400-l90-rj',
		type: 'song',
		videoId: '-0YEJbeTXEk',
	},
	{
		album: { browseId: 'UC-yYvxRAznvkBDg3lKk0qMA', name: 'Sweetaj Brar' },
		artist: 'Sweetaj Brar, Yo Yo Honey Singh, ',
		duration: 193000,
		formatedDuration: '03:13',
		name: 'Care Ni Karda',
		params: 'wAEB',
		playlistId: 'RDAMVMoNahVdI5QKY',
		thumbnails:
			'https://lh3.googleusercontent.com/Ie-hu0WURoSMrCnVT-oUkyA4c1ADVIidv8G8WRS8qIhB9FkvTINuk7a4mc0-tt-pNf30eOfAZqTUoYawvg=w400-h400-l90-rj',
		type: 'song',
		videoId: 'oNahVdI5QKY',
	},
	{
		album: { browseId: 'UCDxKh1gFWeYsqePvgVzmPoQ', name: 'Arijit Singh' },
		artist: 'Arijit Singh',
		duration: 310000,
		formatedDuration: '05:10',
		name: 'Aabaad Barbaad',
		params: 'wAEB',
		playlistId: 'RDAMVMN0ngg3KnFVs',
		thumbnails:
			'https://lh3.googleusercontent.com/z8xvKuuXGpl3t2DGRpQl5c3Y3iT0aP_wnhW6lVT0XiQ0DsZqzrFmEOIJD_hAHRiRrnZK659ieDEbtUbo=w400-h400-l90-rj',
		type: 'song',
		videoId: 'N0ngg3KnFVs',
	},
	{
		album: { browseId: 'UCVfSAUepe_FzP6ge6WexO5Q', name: 'Badshah' },
		artist: 'Badshah',
		duration: 186000,
		formatedDuration: '03:06',
		name: 'Tareefan',
		params: 'wAEB',
		playlistId: 'RDAMVMsJllopnzwdU',
		thumbnails:
			'https://lh3.googleusercontent.com/sm8eZtd6shtLzZF0iwG-6SbV1ua1V4lR44TPTuEfJ6iUHkg8GYmyP09xx5hfMzgvWOB2zarbbTkGVh_KoA=w400-h400-l90-rj',
		type: 'song',
		videoId: 'sJllopnzwdU',
	},
	{
		album: { browseId: 'UCqzQ51ZqgxPvIGGAVUdcuVA', name: 'Tanishk Bagchi' },
		artist: 'Tanishk Bagchi, Yasser Desai, Asees Kaur, ',
		duration: 183000,
		formatedDuration: '03:03',
		name: 'Makhna',
		params: 'wAEB',
		playlistId: 'RDAMVMU13aOFC9Oic',
		thumbnails:
			'https://lh3.googleusercontent.com/PhPhKD8DdRGa_07w2-NqvVXvLoH-O8lmAaoNEwTjoEsJqAPjVJGK8-8jZYXyH7EodYwNXAe1BKcOOFfi=w400-h400-l90-rj',
		type: 'song',
		videoId: 'U13aOFC9Oic',
	},
	{
		album: { browseId: 'UCtJe0RYzgPddQXKtWduxz_w', name: 'A.R. Rahman' },
		artist: 'A.R. Rahman',
		duration: 316000,
		formatedDuration: '05:16',
		name: 'Jashn-E-Bahaaraa',
		params: 'wAEB',
		playlistId: 'RDAMVMcr4Tz4JEP40',
		thumbnails:
			'https://lh3.googleusercontent.com/VyImaqN5k45zum-bIZpoGibHP_ck6-orFQy1b-sLGgjgnE5hx2ErFWnx0b0TbSkTZZAgFUxMRB8rbb1H=w400-h400-l90-rj',
		type: 'song',
		videoId: 'cr4Tz4JEP40',
	},
	{
		album: { browseId: 'UCDxKh1gFWeYsqePvgVzmPoQ', name: 'Arijit Singh' },
		artist: 'Arijit Singh',
		duration: 263000,
		formatedDuration: '04:23',
		name: 'Tum Hi Ho',
		params: 'wAEB',
		playlistId: 'RDAMVMfsiPzT50ZiM',
		thumbnails:
			'https://lh3.googleusercontent.com/Z22ia4zS7X-7gYGGAn_Cog_UycDeMMvNiPXcQM7nHWmMs2D9Uyk7EmyMLnDUe17zptUSeKuCu8bibQ65=w400-h400-l90-rj',
		type: 'song',
		videoId: 'fsiPzT50ZiM',
	},
	{
		album: { browseId: 'UCSPd0Wvy-02QYbZM5QckSag', name: 'Sadhana Sargam' },
		artist: 'Sadhana Sargam',
		duration: 398000,
		formatedDuration: '06:38',
		name: 'Saat Samundar Paar',
		params: 'wAEB',
		playlistId: 'RDAMVMwtlNGAXKkP4',
		thumbnails:
			'https://lh3.googleusercontent.com/rEizufPCr4GlJKva3LhBUA-gXDTeG0JwIlOKZhEO4PL9MQ1foAhOPRH-hyC9AkXxHLK4OkfoXYtKTrZEjQ=w400-h400-l90-rj',
		type: 'song',
		videoId: 'wtlNGAXKkP4',
	},
	{
		album: { browseId: [Array], name: 'Arshad Kamli' },
		artist: '',
		duration: 452000,
		formatedDuration: '07:32',
		name: 'Wo Mujhe Main Use Bhool Jau',
		params: 'wAEB',
		playlistId: 'RDAMVMRggX78sXxio',
		thumbnails:
			'https://lh3.googleusercontent.com/6LrPF1A8evxEo7FAk_nv4cs1bx-KK7fzYs10-ozd5AKroMqDvkk2v7DtLTgO3SFbZkMwC-d1e09WNk8rxA=w400-h400-l90-rj',
		type: 'song',
		videoId: 'RggX78sXxio',
	},
	{
		album: { browseId: 'UCNMewQFJlBeyXpWwo2dezSw', name: 'Darshan Raval' },
		artist: 'Darshan Raval, Neha Kakkar, Manan Bhardwaj, ',
		duration: 262000,
		formatedDuration: '04:22',
		name: 'Teri Aankhon Mein',
		params: 'wAEB',
		playlistId: 'RDAMVMmbJxhvsgwO0',
		thumbnails:
			'https://lh3.googleusercontent.com/17Uipz0gXXLmXF9YDSwVmdUCuqm1Q8WsaRWETs1z97CCOjCOqBazWEsgI21gMrV-mjz85l4EvQoBpk8f3g=w400-h400-l90-rj',
		type: 'song',
		videoId: 'mbJxhvsgwO0',
	},
	{
		album: { browseId: 'UCDxKh1gFWeYsqePvgVzmPoQ', name: 'Arijit Singh' },
		artist: 'Arijit Singh',
		duration: 247000,
		formatedDuration: '04:07',
		name: 'Shayad (From "Love Aaj Kal")',
		params: 'wAEB',
		playlistId: 'RDAMVMEQxEms7gnqs',
		thumbnails:
			'https://lh3.googleusercontent.com/Cr0zxxJ-n5CVF8zYultpi3FCef-BVXkFryW3rJGt6TCOLECklGKAFjLsmuAGdhuVvDUsPdpnnIbgV1RNPQ=w400-h400-l90-rj',
		type: 'song',
		videoId: 'EQxEms7gnqs',
	},
	{
		album: { browseId: 'UCDxKh1gFWeYsqePvgVzmPoQ', name: 'Arijit Singh' },
		artist: 'Arijit Singh',
		duration: 335000,
		formatedDuration: '05:35',
		name: 'Muskurane (Romantic)',
		params: 'wAEB',
		playlistId: 'RDAMVM8MUgi5liyMU',
		thumbnails:
			'https://lh3.googleusercontent.com/-eqGp0IWWM4UiZd5GEbS312wLy8Bf5LDMPphhDoigbpqPPDknb7ww6s4_VJcCBh4gR1YhylUvuRJkRiu=w400-h400-l90-rj',
		type: 'song',
		videoId: '8MUgi5liyMU',
	},
];

export const EnglishSongs = [
	{
		album: { browseId: 'UCeOvrkZes_-LywIjFvbaxug', name: 'H.E.R.' },
		artist: 'H.E.R.',
		duration: 224000,
		formatedDuration: '03:44',
		name: 'damage',
		params: 'wAEB',
		playlistId: 'RDAMVMZq6dTYP4nSQ',
		thumbnails:
			'https://lh3.googleusercontent.com/0otVWK9FkcxIIoXPa_jW3V8udArXBT0kKIGMNNkalF2buSlUx_Cin1m_f7ONFXOgl8RRF0DdqlkRHcc=w400-h400-l90-rj',
		type: 'song',
		videoId: 'Zq6dTYP4nSQ',
	},
	{
		album: { browseId: 'UClmXPfaYhXOYsNn_QUyheWQ', name: 'Ed Sheeran' },
		artist: 'Ed Sheeran',
		duration: 234000,
		formatedDuration: '03:54',
		name: 'Shape of You',
		params: 'wAEB',
		playlistId: 'RDAMVMxTvyyoF_LZY',
		thumbnails:
			'https://lh3.googleusercontent.com/TMbA3LImAL96nFkm5cI1x6LiEMvMbRg4IRxEeABd9qpXsfmwKhZHRD1MucnjG5QIsVEp0Vpn7h7M51FH3Q=w400-h400-l90-rj',
		type: 'song',
		videoId: 'xTvyyoF_LZY',
	},
	{
		album: { browseId: 'UCD3fewmHnwmzjA3IeYWovaQ', name: 'Pop Smoke' },
		artist: 'Pop Smoke',
		duration: 128000,
		formatedDuration: '02:08',
		name: 'Invincible',
		params: 'wAEB',
		playlistId: 'RDAMVMLYz-ktFWZB4',
		thumbnails:
			'https://lh3.googleusercontent.com/TyS1IDFlBoN-b1VBg2_rFa048n2gkPykYwfkQyi9xFjXteIRdMmoYrteGZXpTi8oHDxOOoG5GciH5e8c=w400-h400-l90-rj',
		type: 'song',
		videoId: 'LYz-ktFWZB4',
	},
	{
		album: { browseId: 'UCzdDM4zheCgC3s4WzKhQ4-w', name: 'Luke Combs' },
		artist: 'Luke Combs',
		duration: 194000,
		formatedDuration: '03:14',
		name: 'Beautiful Crazy',
		params: 'wAEB',
		playlistId: 'RDAMVMt6g2tKgF9HQ',
		thumbnails:
			'https://lh3.googleusercontent.com/a0AW9hRSYbmsLVe8jEnm4Q9rHnHeL0hUjfaLvwhZaZC3hQx2IOgbwoEEZjn2PO5G4ZE3nRs1FE61de0=w400-h400-l90-rj',
		type: 'song',
		videoId: 't6g2tKgF9HQ',
	},
	{
		album: { browseId: 'UCm9XijVCOsRrxdx0giD_1fQ', name: 'Mark Ronson' },
		artist: 'Mark Ronson',
		duration: 270000,
		formatedDuration: '04:30',
		name: 'Uptown Funk (feat. Bruno Mars)',
		params: 'wAEB',
		playlistId: 'RDAMVMtYvFa2ARD24',
		thumbnails:
			'https://lh3.googleusercontent.com/-NFtUA6dAmZKAy88a0k88UQ4VrYGKORqYBDSzMKCkwLJy5hgfMk3CppWBP61g6PXmJ69Dm41UNFke9k=w400-h400-l90-rj',
		type: 'song',
		videoId: 'tYvFa2ARD24',
	},
	{
		album: { browseId: 'UCzdDM4zheCgC3s4WzKhQ4-w', name: 'Luke Combs' },
		artist: 'Luke Combs',
		duration: 241000,
		formatedDuration: '04:01',
		name: 'When It Rains It Pours',
		params: 'wAEB',
		playlistId: 'RDAMVMaIVXH31YsDU',
		thumbnails:
			'https://lh3.googleusercontent.com/PQ13eoj9D67MYKAjsAAsEIWom1mMiViPuSII8PiOqfqb441TQU50SpUFvD7sGtewcI5cdqQ0Scjixhk=w400-h400-l90-rj',
		type: 'song',
		videoId: 'aIVXH31YsDU',
	},
	{
		album: { browseId: 'UC7n3gWRN0vQzgiOKc51aZ4w', name: 'KAROL G' },
		artist: 'KAROL G',
		duration: 179000,
		formatedDuration: '02:59',
		name: 'BICHOTA',
		params: 'wAEB',
		playlistId: 'RDAMVMhz7GlXTRh-M',
		thumbnails:
			'https://lh3.googleusercontent.com/uDPGid0kgivESKS-fkfThG8zO5ekPXfaWZtGfZP0sqCQLfezKRm18ZBG-tP9bCrQ2HUkjiuat-rKhkM=w400-h400-l90-rj',
		type: 'song',
		videoId: 'hz7GlXTRh-M',
	},
	{
		album: { browseId: 'UCD3fewmHnwmzjA3IeYWovaQ', name: 'Pop Smoke' },
		artist: 'Pop Smoke',
		duration: 160000,
		formatedDuration: '02:40',
		name: 'What You Know Bout Love',
		params: 'wAEB',
		playlistId: 'RDAMVMjhTkV1r2Mpg',
		thumbnails:
			'https://lh3.googleusercontent.com/7xqYdHOUp2IiQOdbkT3OOg1F4luzkWRtzH9DCcpdBS0rcY3Rf_dp6MdLMSS4R308ZAbgwp0-AkmjNVv3=w400-h400-l90-rj',
		type: 'song',
		videoId: 'jhTkV1r2Mpg',
	},
	{
		album: { browseId: 'UCxrxwFTBU3DTJ9Y5TKeW7KA', name: 'Lewis Capaldi' },
		artist: 'Lewis Capaldi',
		duration: 183000,
		formatedDuration: '03:03',
		name: 'Someone You Loved',
		params: 'wAEB',
		playlistId: 'RDAMVMpRIZohFFOMo',
		thumbnails:
			'https://lh3.googleusercontent.com/DJE9ox7ulDe30gFXprMbbeFyXuivmp2xiMFU1SQ0KzQIqFl2PBMcDHjPD-3fjLq8J1P58fbo-NGRMLBpVg=w400-h400-l90-rj',
		type: 'song',
		videoId: 'pRIZohFFOMo',
	},
	{
		album: { browseId: 'UCGvj8kfUV5Q6lzECIrGY19g', name: 'Justin Bieber' },
		artist: 'Justin Bieber',
		duration: 213000,
		formatedDuration: '03:33',
		name: 'Intentions (feat. Quavo)',
		params: 'wAEB',
		playlistId: 'RDAMVMRcSX0hOWcQ0',
		thumbnails:
			'https://lh3.googleusercontent.com/RWp6xYchtFg37DeLr-yxYOE6qWcPYApWuXkk3EYm_RLoqTtCTv-qPOyAy1F8wWjjiD1ZA99lmIrTAxs=w400-h400-l90-rj',
		type: 'song',
		videoId: 'RcSX0hOWcQ0',
	},
	{
		album: { browseId: 'UCxrxwFTBU3DTJ9Y5TKeW7KA', name: 'Lewis Capaldi' },
		artist: 'Lewis Capaldi',
		duration: 216000,
		formatedDuration: '03:36',
		name: 'Before You Go',
		params: 'wAEB',
		playlistId: 'RDAMVMQQVa4xCf8JY',
		thumbnails:
			'https://lh3.googleusercontent.com/NbtQPGhtq1iG1sreQi6fa0iKiZi3Uc0zLVbhO2Vd36srp0LmlbDYMuVSfs9el3JWRVS5xUcRbpnAjfY=w400-h400-l90-rj',
		type: 'song',
		videoId: 'QQVa4xCf8JY',
	},
	{
		album: { browseId: 'UCzdDM4zheCgC3s4WzKhQ4-w', name: 'Luke Combs' },
		artist: 'Luke Combs',
		duration: 184000,
		formatedDuration: '03:04',
		name: 'She Got the Best of Me',
		params: 'wAEB',
		playlistId: 'RDAMVMXltdUnThFfw',
		thumbnails:
			'https://lh3.googleusercontent.com/a0AW9hRSYbmsLVe8jEnm4Q9rHnHeL0hUjfaLvwhZaZC3hQx2IOgbwoEEZjn2PO5G4ZE3nRs1FE61de0=w400-h400-l90-rj',
		type: 'song',
		videoId: 'XltdUnThFfw',
	},
	{
		album: { browseId: 'UCD3fewmHnwmzjA3IeYWovaQ', name: 'Pop Smoke' },
		artist: 'Pop Smoke',
		duration: 191000,
		formatedDuration: '03:11',
		name: 'For The Night (feat. Lil Baby & DaBaby)',
		params: 'wAEB',
		playlistId: 'RDAMVMFkXulkASrqc',
		thumbnails:
			'https://lh3.googleusercontent.com/rhFVf2CHG2mDAcp7-EezmCk20RwziT-sh5kKoZOUWv9Q1tPEfY75wq6Q8VLuPJsdGQ5MZt522Xpw0jGH=w400-h400-l90-rj',
		type: 'song',
		videoId: 'FkXulkASrqc',
	},
	{
		album: { browseId: 'UCD3fewmHnwmzjA3IeYWovaQ', name: 'Pop Smoke' },
		artist: 'Pop Smoke',
		duration: 191000,
		formatedDuration: '03:11',
		name: 'Hello (feat. A Boogie wit da Hoodie)',
		params: 'wAEB',
		playlistId: 'RDAMVMBvMNjpDF2SY',
		thumbnails:
			'https://lh3.googleusercontent.com/HPlDsYCnkO7dThaIcaFappiA1l1lMcwEp-EhvkREQWVHGA0cPncZJEWzSTH9juteoaQavQK9LyaT6YM=w400-h400-l90-rj',
		type: 'song',
		videoId: 'BvMNjpDF2SY',
	},
	{
		album: { browseId: 'UCD3fewmHnwmzjA3IeYWovaQ', name: 'Pop Smoke' },
		artist: 'Pop Smoke',
		duration: 202000,
		formatedDuration: '03:22',
		name: 'The Woo (feat. 50 Cent & Roddy Ricch)',
		params: 'wAEB',
		playlistId: 'RDAMVM-Gkp-B7rIxY',
		thumbnails:
			'https://lh3.googleusercontent.com/rhFVf2CHG2mDAcp7-EezmCk20RwziT-sh5kKoZOUWv9Q1tPEfY75wq6Q8VLuPJsdGQ5MZt522Xpw0jGH=w400-h400-l90-rj',
		type: 'song',
		videoId: '-Gkp-B7rIxY',
	},
	{
		album: { browseId: 'UCZn4r7heNOPY-C43YIywnVA', name: 'Bruno Mars' },
		artist: 'Bruno Mars',
		duration: 218000,
		formatedDuration: '03:38',
		name: 'Talking to the Moon',
		params: 'wAEB',
		playlistId: 'RDAMVMlIaDtfplmyQ',
		thumbnails:
			'https://lh3.googleusercontent.com/-MBagZMcp-AsKziX22bIEvPjNlxPPyU8hgXC07dXlt9GmlBTA1hZI9yyAuCP0mswnSBNRMOvoI1y9_Y=w400-h400-l90-rj',
		type: 'song',
		videoId: 'lIaDtfplmyQ',
	},
	{
		album: { browseId: 'UCD3fewmHnwmzjA3IeYWovaQ', name: 'Pop Smoke' },
		artist: 'Pop Smoke',
		duration: 214000,
		formatedDuration: '03:34',
		name: 'Mood Swings (feat. Lil Tjay)',
		params: 'wAEB',
		playlistId: 'RDAMVMBwQZTGMvYoY',
		thumbnails:
			'https://lh3.googleusercontent.com/rhFVf2CHG2mDAcp7-EezmCk20RwziT-sh5kKoZOUWv9Q1tPEfY75wq6Q8VLuPJsdGQ5MZt522Xpw0jGH=w400-h400-l90-rj',
		type: 'song',
		videoId: 'BwQZTGMvYoY',
	},
	{
		album: {
			browseId: 'UCEBTD8bc2J7wG7Fqhss7Jow',
			name: 'Chris Stapleton',
		},
		artist: 'Chris Stapleton',
		duration: 294000,
		formatedDuration: '04:54',
		name: 'Tennessee Whiskey',
		params: 'wAEB',
		playlistId: 'RDAMVMl6_w3887Rwo',
		thumbnails:
			'https://lh3.googleusercontent.com/nEkBfOAc02tKzDZ1m-jLwgT0udQxJld0qI6dFy1BW2ff5B0dHBYALAP6rtjKledbdGpZybh6fZK0QoeDKw=w400-h400-l90-rj',
		type: 'song',
		videoId: 'l6_w3887Rwo',
	},
	{
		album: { browseId: 'UCxrxwFTBU3DTJ9Y5TKeW7KA', name: 'Lewis Capaldi' },
		artist: 'Lewis Capaldi',
		duration: 206000,
		formatedDuration: '03:26',
		name: 'Hold Me While You Wait',
		params: 'wAEB',
		playlistId: 'RDAMVMarj4BDdz6qc',
		thumbnails:
			'https://lh3.googleusercontent.com/DJE9ox7ulDe30gFXprMbbeFyXuivmp2xiMFU1SQ0KzQIqFl2PBMcDHjPD-3fjLq8J1P58fbo-NGRMLBpVg=w400-h400-l90-rj',
		type: 'song',
		videoId: 'arj4BDdz6qc',
	},
];
